### ISSUE TITLE
The bug of eval code

### ISSUE THREAD

**Issue by JosonChan1998** [Andy1621/Kinetics-TPS-evaluation#1]
Hi ! Thanks for your implement of kinetics-TPS evaluation.

When I use the code to eval my method, I got a error:
```
Traceback (most recent call last):
  File "utils/eval_psc_new.py", line 272, in <module>
    eval()
  File "utils/eval_psc_new.py", line 256, in eval
    part_vid_acc = cal_task_acc(gt_vid_result, gt_part_result, pred_vid_result, pred_part_result, 
  File "utils/eval_psc_new.py", line 245, in cal_task_acc
    video_part_acc_avg = eval_video_TPS(vid, gt_part_result, pred_part_result, 
  File "utils/eval_psc_new.py", line 220, in eval_video_TPS
    human_part_acc_sum = eval_human_TPS(gt_human, match_human_info[i][2], match_human_info[i][1],
  File "utils/eval_psc_new.py", line 187, in eval_human_TPS
    part_iou = part_ious[j] if USE_BATCH_IOU else bbox_iou(gt_part_box, pred_part_box)
  File "utils/eval_psc_new.py", line 19, in bbox_iou
    xA = max(boxA[0], boxB[0])
TypeError: '>' not supported between instances of 'list' and 'int'
```
I found out that the error comes from the following code:
https://github.com/Andy1621/Kinetics-TPS-evaluation/blob/1124bf9d3d41cc0e9dd8ead595324a6e38fa14ed/eval_detection.py#L176-L177

Could you please give me some suggestion about it?

**Comment by Andy1621** [comment]
Thanks for your question! Can you comment delete such two lines and see whether it is normal?

This repo is forked from [xiading](https://github.com/xiadingZ/Kinetics-TPS-evaluation), he delete such two lines, but in my experiments, I got an error when not using them.

**Comment by JosonChan1998** [comment]
After I delete such two lines, it works for me. 
Did you use the ground truth labels as pred result for testing?

**Comment by JosonChan1998** [comment]
> Thanks for your question! Can you comment delete such two lines and see whether it is normal?
> 
> This repo is forked from [xiading](https://github.com/xiadingZ/Kinetics-TPS-evaluation), he delete such two lines, but in my experiments, I got an error when not using them.

After I delete such two lines, it works for me.
Did you use the ground truth labels as pred result for testing?

**Comment by JosonChan1998** [comment]
Also, I got an error when I upload the test result to the colab sever：

```
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpc3bcOV/run/program/eval_detection.py", line 282, in <module>
    area = eval(truth_dir,submit_dir)
  File "/tmp/codalab/tmpc3bcOV/run/program/eval_detection.py", line 256, in eval
    max_human_iou=0.5, max_part_iou=0.3)
  File "/tmp/codalab/tmpc3bcOV/run/program/eval_detection.py", line 242, in cal_task_acc
    pred_cla = pred_vid_result[vid]
KeyError: u'0835'

```
It looks like gt_vid_result has the wrong key inside, can you test it properly in your experiments?

https://github.com/xiadingZ/Kinetics-TPS-evaluation/blob/b6fb668f680e81522d64759baa01c787af32bc07/eval_detection.py#L242-L243

**Comment by Andy1621** [comment]
Yes, such code is used for the [ECCV2022 DeeperAction Challenge track4](https://codalab.lisn.upsaclay.fr/competitions/4392), welcome to join it~~

**Comment by Andy1621** [comment]
I have seen you test log, I will check it~~

**Comment by JosonChan1998** [comment]
> Yes, such code is used for the [ECCV2022 DeeperAction Challenge track4](https://codalab.lisn.upsaclay.fr/competitions/4392), welcome to join it~~

Thanks for your reply ! 

So I need to delete such two line code, right?

**Comment by Andy1621** [comment]
I have downloaded your submissions, it seems that you used the old version of dataset. In the new version, we have changed the file name and put all the videos in one directory!

**Comment by Andy1621** [comment]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/24236723/166247969-371b9af8-0247-4f0c-bd27-0a0b9c37c87b.png">
Please check the dataset structure~~

**Comment by Andy1621** [comment]
> > Yes, such code is used for the [ECCV2022 DeeperAction Challenge track4](https://codalab.lisn.upsaclay.fr/competitions/4392), welcome to join it~~
> 
> Thanks for your reply !
> 
> So I need to delete such two line code, right?

Yes, I have deleted these two codes and it runs normally. The error may occur because you used the old version of dataset~~

**Comment by JosonChan1998** [comment]
> I have downloaded your submissions, it seems that you used the old version of dataset. In the new version, we have changed the file name and put all the videos in one directory!

But I have download the list from new version, and I found the video test_flist.csv is the same with the old version. 

I download the video_test_flist.csv from baidu link.

**Comment by Andy1621** [comment]
Thanks for your feedback! I have updated the wrong downloaded link for BaiduYun. And the link for Google Drive is right.

**Comment by JosonChan1998** [comment]
> Thanks for your feedback! I have updated the wrong downloaded link for BaiduYun. And the link for Google Drive is right.

Ok, I have downloaded the updated datasets. I will check it. Thanks!

**Comment by JosonChan1998** [comment]
Sorry for reopen the issue.

I have downloaded the new datasets from baidu link. But I can't find  the action labels of train videos. 
Since the video's filename is changed to xxxx.mp4 and the action label is lost.

**Comment by JosonChan1998** [comment]
Hi! I got an error when I upload my new result.

Could you please help me check the error ?

```
Traceback (most recent call last):
  File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 282, in 
    area = eval(truth_dir,submit_dir)
  File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 256, in eval
    max_human_iou=0.5, max_part_iou=0.3)
  File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 245, in cal_task_acc
    max_human_iou, max_part_iou)
  File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 220, in eval_video_TPS
    max_human_iou, max_part_iou)
  File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 187, in eval_human_TPS
    part_iou = part_ious[j] if USE_BATCH_IOU else bbox_iou(gt_part_box, pred_part_box)
  File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 20, in bbox_iou
    yA = max(boxA[1], boxB[1])
IndexError: list index out of range
```

**Comment by Soptq** [comment]
> Hi! I got an error when I upload my new result.
> 
> Could you please help me check the error ?
> 
> ```
> Traceback (most recent call last):
>   File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 282, in 
>     area = eval(truth_dir,submit_dir)
>   File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 256, in eval
>     max_human_iou=0.5, max_part_iou=0.3)
>   File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 245, in cal_task_acc
>     max_human_iou, max_part_iou)
>   File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 220, in eval_video_TPS
>     max_human_iou, max_part_iou)
>   File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 187, in eval_human_TPS
>     part_iou = part_ious[j] if USE_BATCH_IOU else bbox_iou(gt_part_box, pred_part_box)
>   File "/tmp/codalab/tmpR54Hje/run/program/eval_detection.py", line 20, in bbox_iou
>     yA = max(boxA[1], boxB[1])
> IndexError: list index out of range
> ```

Same problem, did you sort it out?
